[package]
name = "gps_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../../../ex3_shared_libs/common"}
ipc = { path = "../../../ex3_shared_libs/interfaces/ipc" }
log = "0.4.22"
logging = { path = "../../../ex3_shared_libs/logging" }
