[package]
name = "gui_ground_station"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
stylist = { version = "0.13", features= ["yew"] }