[workspace]

members = [
    "handlers/handler",
    "libs/interfaces",
    "libs/message_structure",
    "scheduler",
    "handlers/dfgm_handler",
    "libs/common", 
    "dev_tools/cli_test_msg", 
    "dev_tools/ipc_dummy_client",
]
