[workspace]

members = [
    "handlers/handler",
    "libs/tcp_interface",
    "libs/message_structure",
    "scheduler",
    "handlers/dfgm_handler",
    "libs/common", 
    "dev_tools/cli_test_msg", 
    "dev_tools/ipc_dummy_client",
    "libs/ipc_interface",
]
