[package]
name = "bulk_msg_dispatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
interface = { path = "../../ex3_shared_libs/interface" }
common = {path = "../../ex3_shared_libs/common"}
log = "0.4.22"
