[workspace]

members = [
    "scheduler",
    "handlers/dfgm_handler",
    "handlers/coms_handler",
    "dev_tools/cli_test_msg",
    "dev_tools/ipc_dummy_client",
    "dev_tools/ipc_burst_hardcoded",
]
