[package]
name = "coms_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../../ex3_shared_libs/common" }
interface = { path = "../../../ex3_shared_libs/interface" }
log = "0.4.22"
