[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
log = "0.4.22"
log4rs = "1.3.0"
