[package]
name = "iris_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
interface = { path = "../../../ex3_shared_libs/interface" }
common = {path = "../../../ex3_shared_libs/common"}
nix = "0.26.2"
serde_json = "1.0.125"
log = "0.4.22"
