[package]
name = "uart_interface"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.2"
message_structure = { path = "../message_structure" }
rand = "0.8.5"
serialport = "4.0"
