[package]
name = "ipc_server_dev_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
message_structure = { path = "../../../ex3_shared_libs/message_structure" }
common = { path = "../../../ex3_shared_libs/common" }
interfaces = { path = "../../../ex3_shared_libs/interfaces" }
nix = "0.26.2"
