[package]
name = "interface"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["poll", "socket", "fs"] }
i2cdev = "0.6.1"
spidev = "0.6.0"
serialport = "4.6.0"
common = {path = "../common"}

