on: [push]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
        env:
          RUSTFLAGS: "-D warnings"
      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
        env:
          RUSTFLAGS: "-D warnings"
